### ISSUE TITLE
Implementing Video Component Integration with DatoCMS

### ISSUE THREAD

**Issue by thijsvandiessen** [crea-orkest/crea-public#146]
Currently, the video component is not yet implemented, and there is a need to explore standard implementations for DatoCMS videos. The placeholder code provided below needs to be replaced with a functional video component.

**Acceptance Criteria:**

**Video Component Integration:**
   - [ ] Explore standard implementations for DatoCMS videos to understand best practices and available options.
   - [ ] Replace the placeholder code with a functional video component that integrates seamlessly with DatoCMS.
   - [ ] Ensure the video component is capable of handling different video formats and resolutions for optimal user experience.
   - [ ] Implement error handling to gracefully manage scenarios where the video URL is unavailable or invalid.

**Placeholder Code:**
```jsx
if (isOfType<VideoFragment>(record, 'VideoRecord')) {
    if (!record.media?.url) return null
    return <p>some video component</p>
}

**Comment by velomovies** [comment]
Yes, I've something standard

**Comment by velomovies** [comment]
I have an on the shelf implementation which ticks al the boxes

**Comment by thijsvandiessen** [comment]
done
