### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by thijsvandiessen** [crea-orkest/crea-public#87]
There is no footer component yet that we could edit in our cms. So also no footer component within this repo. 

I think all socials and a couple of important links should be there always, like contact.

**Comment by velomovies** [comment]
The footer isn't a component from the cms since it only has info from the general info model in the CMS. 

It will show the main items from the navigation, the address and some socials. (only the socials should be added in the general info in the cms I think)

**Comment by thijsvandiessen** [comment]
yea, maybe we could wrap the menu, so that we could create a main and secondary menu. Or... add a simple list to the general component. Not sure if I want to hard code this, but that could also be an option.

**Comment by velomovies** [comment]
I think using the main items from the main menu should be sufficient

**Comment by thijsvandiessen** [comment]
done
